-- Safe to run repeatedly in the Supabase SQL editor or with `supabase db push`.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null check (username = lower(username)),
  display_name text,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  username text not null,
  title text not null,
  author text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Stable application contract for books.metadata (JSON property names are
-- case-sensitive). title and author deliberately remain searchable columns;
-- metadata.authors is the ordered, lossless author list and author is its
-- comma-separated display value. The application writes every key below, even
-- when its value is the documented empty default:
--   subtitle text = ''                 authors text[] = []
--   isbns text[] = []                  publishers text[] = []
--   publishedDate text = ''            pageCount number|null = null
--   subjects text[] = []               synopsis text = ''
--   cover_url text = ''                coverOptions text[] = []
--   source text = ''                   isRead boolean = false
--   startedDate text = ''              finishedDate text = ''
--   rating number (0..5) = 0           review text = ''
--   shelfSlot integer|null = null       render object = {}
--   addedAt text = ''                   translatedSynopsis boolean = false
-- Dates are ISO-8601 date strings when present. `render` contains renderer
-- preferences (dimensions, colors, and size/thickness categories) and is
-- intentionally extensible. Readers normalize missing/invalid values to these
-- defaults. Legacy `isbn` and `status` keys are read for compatibility; notably
-- status = 'Read' becomes isRead = true, but new writes use isbns and isRead.
comment on column public.books.metadata is
  'Stable Bexs Library book details contract. Keys: subtitle text; authors text[]; isbns text[]; publishers text[]; publishedDate text; pageCount number|null; subjects text[]; synopsis text; cover_url text; coverOptions text[]; source text; isRead boolean; startedDate text; finishedDate text; rating number 0..5; review text; shelfSlot integer|null; render object; addedAt text; translatedSynopsis boolean. Missing keys use application defaults. Legacy status/isbn are read-only compatibility aliases.';

alter table public.profiles enable row level security;
alter table public.books enable row level security;

-- PostgreSQL does not support CREATE POLICY IF NOT EXISTS. Drop each policy first
-- so this complete schema can also update a database that was partially set up.
drop policy if exists "Members read their profile" on public.profiles;
drop policy if exists "Members read their books" on public.books;
drop policy if exists "Members add their books" on public.books;
drop policy if exists "Members update their books" on public.books;
drop policy if exists "Members delete their books" on public.books;

create policy "Members read their profile" on public.profiles for select to authenticated using (id = auth.uid());
create policy "Members read their books" on public.books for select to authenticated using (user_id = auth.uid());
create policy "Members add their books" on public.books for insert to authenticated with check (user_id = auth.uid() and username = (select username from public.profiles where id = auth.uid()));
create policy "Members update their books" on public.books for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Members delete their books" on public.books for delete to authenticated using (user_id = auth.uid());

-- Creates the profile automatically. Authentication uses the user's full email;
-- username remains an internal, lowercase owner label for catalogue records.
create or replace function public.create_member_profile()
returns trigger language plpgsql security definer set search_path = public
as $$ begin insert into profiles (id, username, display_name, avatar_url) values (new.id, split_part(new.email, '@', 1), coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)), new.raw_user_meta_data->>'avatar_url'); return new; end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.create_member_profile();
