-- Run this once in the Supabase SQL editor or with `supabase db push`.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null check (username = lower(username)),
  display_name text,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  username text not null,
  title text not null,
  author text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.books enable row level security;
create policy "Members read their profile" on public.profiles for select to authenticated using (id = auth.uid());
create policy "Members read their books" on public.books for select to authenticated using (user_id = auth.uid());
create policy "Members add their books" on public.books for insert to authenticated with check (user_id = auth.uid() and username = (select username from public.profiles where id = auth.uid()));
create policy "Members update their books" on public.books for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Members delete their books" on public.books for delete to authenticated using (user_id = auth.uid());

-- Returns only card artwork/name for an exact username. It never exposes email,
-- password data, user UUIDs, or the profiles table itself to anonymous visitors.
create or replace function public.preview_member_card(requested_username text)
returns table (username text, display_name text, avatar_url text)
language sql security definer stable set search_path = public
as $$ select p.username, p.display_name, p.avatar_url from profiles p where p.username = lower(trim(requested_username)) limit 1 $$;
revoke all on function public.preview_member_card(text) from public;
grant execute on function public.preview_member_card(text) to anon, authenticated;

-- Creates the profile automatically. Member emails use username@members.bexslibrary.app.
create or replace function public.create_member_profile()
returns trigger language plpgsql security definer set search_path = public
as $$ begin insert into profiles (id, username, display_name, avatar_url) values (new.id, split_part(new.email, '@', 1), coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)), new.raw_user_meta_data->>'avatar_url'); return new; end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.create_member_profile();
